### ISSUE TITLE
Hola, me puede ayudar con Dorn

### ISSUE THREAD

**Issue by AnakinProgrammit** [Kemquiros/DORN#1]
Hey, veo que estas haciendo un juego bien bacano. Podemos hablar en whatsapp? 829-629-9148, necesito una ayuda con el juego Dorn.

**Comment by Kemquiros** [comment]
Hola, dime en qué te puedo ayudar.

**Comment by AnakinProgrammit** [comment]
Estoy en Republica Dominicana y no tengo posibilidad de comprar Dorn, entonces lo quiero imprimir porque lo amo y lo jugaba cuando estaba en Europa, pero no hayo documentos ni pdf con elmapa o las tarjetitas de hechizos y heroes. 

Te quería preguntar si tu me puedes hacer fotos de todo en HD para yo imprimir lo.

Te puedo enviar crypto monedas como BTC o ETH si quieres.

**Comment by Kemquiros** [comment]
Mira, en este foro se encuentra la versión P&P (Print and Play) del juego:
http://labsk.net/index.php?topic=21677.0

**Comment by AnakinProgrammit** [comment]
Te amo!! Lo unico que falta es el mapa, no veo el mapa sin las indicaciones de la guía. Solo, guía, cartas y heroes.

**Comment by AnakinProgrammit** [comment]
Digo el tablero de 4, todos los enlaces no están funcionando

**Comment by AnakinProgrammit** [comment]
No sabes donde puedo hallar el mapa?

**Comment by Kemquiros** [comment]
Hola, no sé cuáles links funcionan en el foro pero puedes imprimir este que tiene buena resolución -> https://raw.githubusercontent.com/Kemquiros/DORN/master/src/com/dorn/assets/map/mapa_escalado.jpg

**Comment by AnakinProgrammit** [comment]
Excelente!! Yo soy un programador web entonces si vas a necesitar una pagina cuando terminas el juego me avisas :) <333

**Comment by Kemquiros** [comment]
Listo man, mil gracias por el (futuro) apoyo !
:)
